let Students = [{
        id: 1,
        name: "Flinn Hunt",
        progress: "lesson 3",
        email: "taylormdavidson97@gmail.com",
        phone: "(801) 771 - 4064" ,
        image: 'mugs.jpg',
        day: "Monday",
        homework: "2.5",
        },
        {
        id: 2,
        name: "Flinn Hoot",
        progress: "lesson 2",
        email: "taylormdavidson97@gmail.com",
        phone: "(801) 771 - 4064" ,
        image: 'mugs.jpg',
        day: "Tuesday",
        homework: "2.6", 
	},	
	{
	id: 3,
        name: "Flinn H.",
        progress: "lesson 1",
        email: "taylormdavidson97@gmail.com",
        phone: "(801) 771 - 4064" ,
        image: 'mugs.jpg',
        day: "Wednesday",
        homework: "5.1",
        },
        {
        id: 4,
        name: "Flinn",
        progress: "lesson 3",
        email: "taylormdavidson97@gmail.com",
        phone: "(801) 771 - 4064" ,
        image: 'mugs.jpg',
        day: "Thursday",
        homework: "1.0",
	},
	{
	id: 5,
        name: "Fli unt",
        progress: "lesson 10",
        email: "taylormdavidson97@gmail.com",
        phone: "(801) 771 - 4064" ,
        image: 'mugs.jpg',
        day: "Monday",
        homework: "2.0",
        },
]

export default Students;
